"""empty message

Revision ID: 97306608400a
Revises: f57ada1f155d
Create Date: 2021-05-09 10:48:04.426732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97306608400a'
down_revision = 'f57ada1f155d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todolists', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todolists', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
